[package]
name = "anchr"
version = "0.3.17"
authors = ["wang-q <wang-q@outlook.com>"]
edition = "2018"
description = "Assembler of N-free CHRomosomes"
documentation = "https://github.com/wang-q/anchr"
readme = "README.md"
homepage = "https://github.com/wang-q/anchr"
repository = "https://github.com/wang-q/anchr"
license = "None"
categories = ["command-line-utilities", "bioinformatics"]
publish = false

[[bin]]
name = "anchr"
path = "src/anchr.rs"

[dependencies]
clap = "2"
tera = "1"
intspan = "0.4.14"
itertools = "0.9.0"

[build-dependencies]

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11"
predicates = "1"

[profile.release]
lto = true
