#!/usr/bin/env bash

# verify-migrate.sh
# Dual-track golden check for the fq/asm migration from pgr (stage 3 of
# notes/design/fq-asm-migrate.md): for every migrated command, run the same
# input through anchr and pgr and require byte-identical outputs.
#
# NOTE (2026-08-13): the migration is complete and pgr has removed the
# fq/asm/sam commands, so a rebuilt `pgr` binary no longer has them. This
# script is kept as the historical stage-3 verification tool; it only runs
# against a pgr binary built before the removal (e.g. the stale debug
# binary, which still carries fq/asm/sam).
#
# Requires:
#   - anchr binary (prefers target/release, falls back to target/debug;
#     use ANCHR=... to override)
#   - pgr binary (sibling checkout ../pgr, same release/debug preference;
#     use PGR=... to override)
#
# Usage:
#   scripts/verify-migrate.sh

set -uo pipefail

cd "$(dirname "$0")/.."

ANCHR="${ANCHR:-}"
if [ -z "$ANCHR" ] && [ -x "$PWD/target/release/anchr" ]; then
    ANCHR="$PWD/target/release/anchr"
else
    ANCHR="${ANCHR:-$PWD/target/debug/anchr}"
fi

PGR="${PGR:-}"
if [ -z "$PGR" ] && [ -x "$PWD/../pgr/target/release/pgr" ]; then
    PGR="$PWD/../pgr/target/release/pgr"
else
    PGR="${PGR:-$PWD/../pgr/target/debug/pgr}"
fi

D="$PWD/tests/bbtools/Lambda"
G="$D/golden"
W=$(mktemp -d)
PASS=0
FAIL=0

cmp() {
    local name="$1"
    shift
    rm -rf "$W/$name.a" "$W/$name.b"
    mkdir -p "$W/$name.a" "$W/$name.b"
    (cd "$W/$name.a" && if "$ANCHR" "$@" >out.stdout 2>out.stderr; then echo 0 >rc; else echo $? >rc; fi)
    (cd "$W/$name.b" && if "$PGR" "$@" >out.stdout 2>out.stderr; then echo 0 >rc; else echo $? >rc; fi)
    # Normalize env_logger lines: drop timestamp and module path (crate name
    # differs between anchr and pgr); keep level + message.
    sed -E 's/^\[[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]+Z (INFO|WARN|ERROR|DEBUG|TRACE) +[^]]+\]/\1/' \
        "$W/$name.a/out.stderr" >"$W/$name.a/out.stderr.norm"
    sed -E 's/^\[[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]+Z (INFO|WARN|ERROR|DEBUG|TRACE) +[^]]+\]/\1/' \
        "$W/$name.b/out.stderr" >"$W/$name.b/out.stderr.norm"
    rm -f "$W/$name.a/out.stderr" "$W/$name.b/out.stderr"
    local arc prc
    arc=$(cat "$W/$name.a/rc")
    prc=$(cat "$W/$name.b/rc")
    if [ "$arc" == "$prc" ] && diff -rq "$W/$name.a" "$W/$name.b" >/dev/null; then
        PASS=$((PASS + 1))
        echo "PASS $name"
    else
        FAIL=$((FAIL + 1))
        echo "FAIL $name (rc $arc vs $prc)"
        diff -rq "$W/$name.a" "$W/$name.b" | head -6
    fi
}

# ---- batch 1: fq basics ----
cmp fq_tofa       fq to-fa "$D/R1.2k.fq.gz"
cmp fq_interleave fq interleave "$D/R1.2k.fq.gz" "$D/R2.2k.fq.gz"
cmp fq_sample     fq sample "$G/filter.fq.gz" -o sample.out --bases 1000000 --seed 1
cmp fq_clump      fq clump "$D/R1.fq.gz" "$D/R2.fq.gz" -o clump.out
cmp fq_trimqual   fq trim-qual "$D/R1.2k.fq.gz" -o trimqual.out
cmp fq_clean      fq clean "$D/R1.2k.fq.gz" -o clean.out
cmp fq_filter     fq filter "$G/trim.fq.gz" --ref "$D/illumina_adapters.fa" --k 27 -o filter.out
cmp fq_merge      fq merge "$G/ext_sub.fq.gz" -o merge.out --outu merge.u.out --ihist merge.ihist --strict --no-make-vector --extend2 80 --rem
cmp fq_norm       fq norm "$D/R1.fq.gz" -o norm.out
cmp asm_unitig    asm unitig "$PWD/tests/ovlpr/1_4.pac.fasta" -o unitigs.out --kmer 31
cmp asm_contig    asm contig "$PWD/tests/ovlpr/1_4.pac.fasta" -o contigs.out --kmer 31

# ---- batch 2: fq error correction + asm map ----
cmp fq_ec_kmer    fq ec-kmer "$G/ecco_sub.fq.gz" -o ecco.out --toss-junk --toss-depth 2 --toss-uncorrectable
cmp fq_extend     fq extend "$G/ecco_sub.fq.gz" -o ext.out --kmer 62 --el 20 --er 20
cmp fq_s_filter   fq s-filter "$G/filter.fq.gz" -k 31 -o kept.out --discard-file discarded.out
cmp fq_ec_overlap fq ec-overlap "$D/R1.2k.fq.gz" "$D/R2.2k.fq.gz" -o eco.out --outu eco.u.out --vstrict --no-make-vector
# Plain-text FASTQ: the `.loc` index is built automatically; BGZF inputs
# additionally need a `.gzi` sidecar generated by pgr's bgzf library.
printf '@r1\nACGTACGT\n+\n!!!!!!!!\n@r2\nTGCA\n+\n!!!!\n' >"$W/in.fq"
cmp fq_range       fq range "$W/in.fq" r2 r1 -o range.out
printf '@r1/1 c1\nACGT\n+\n!!!!\n@r1/2 c1\nTGCA\n+\n!!!!\n@r2/1 c2\nGGGG\n+\n!!!!\n@r2/2 c2\nCCCC\n+\n!!!!\n@r3/1 c3\nTTTT\n+\n!!!!\n' >"$W/in.il.fq"
cmp fq_split       fq split "$W/in.il.fq" -o r1.out --outfile-2 r2.out --outfile-single s.out

printf '>a\nACGTACGTACGTACGTACGT\n>b\nACGTACGTACGTACGT\n' >"$W/a.fa"
printf '>b\nACGTACGTACGTACGT\n>c\nACGTACGTACGTACGTACGTACGT\n' >"$W/b.fa"
printf '@r1\nAAAAAAAAAACCCCCCCCCCGGGGGGGGGG\n+\nIIIIIIIIIIIIIIIIIIIIIIIIIIIIII\n@r2\nGGGGGGGGGGTTTTTTTTTTTTTTTTTTTT\n+\nIIIIIIIIIIIIIIIIIIIIIIIIIIIIII\n' >"$W/reads.fq"
printf '>ref\nACGTACGTACGTACGTACGTACGTACGTACGT\n' >"$W/ref.fa"

cmp asm_ovlp      asm ovlp "$W/a.fa" "$W/b.fa" --overlap-k 5 --min-overlap 8
cmp asm_olc       asm olc "$D/R1.2k.fq.gz" "$D/R2.2k.fq.gz" -o olc.out --kmer 21,51 --min-contig-len 100
cmp asm_map       asm map "$W/ref.fa" "$W/reads.fq" --outm map.out.sam --outu map.outu -k 31

# ---- batch 3: OLC stages on shared unitigs ----
printf '>unitig_1\nAAAAAAAAACGTACGT\n>unitig_2\nACGTACGTCCCCCCCC\n>unitig_3\nCCCCCCCCGGGGGGGG\n' >"$W/ut.fa"
if [ ! -f "$W/ovlp.paf" ]; then
    (cd "$W" && "$ANCHR" asm ovlp ut.fa --overlap-k 5 --min-overlap 8 -o ovlp.paf)
fi
cmp asm_layout    asm layout "$W/ovlp.paf" "$W/ut.fa" -o layout.tsv
cp "$W/asm_layout.a/layout.tsv" "$W/layout.tsv"
cmp asm_cns       asm cns "$W/layout.tsv" "$W/ut.fa" -o cns.fa

# ---- batch 4: sam group (ihist / to-rg) ----
printf '@HD\tVN:1.6\tSO:unknown\n@SQ\tSN:ut\tLN:1000\np1\t67\tut\t11\t255\t31M\t=\t31\t70\tACGT\tIIII\np1\t147\tut\t31\t255\t31M\t=\t11\t-70\tACGT\tIIII\np2\t67\tut\t101\t255\t31M\t=\t121\t70\tACGT\tIIII\np2\t147\tut\t121\t255\t31M\t=\t101\t-70\tACGT\tIIII\n' >"$W/in.sam"
cmp sam_to_rg     sam to-rg "$W/in.sam"
cmp sam_ihist     sam ihist "$W/in.sam"

echo "PASS=$PASS FAIL=$FAIL"
echo "workdir=$W"
